export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const ADD_FLASH_MEASSAGE = 'ADD_FLASH_MEASSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const EVENT_CREATED = 'EVENT_CREATED';
export const ALL_EVENTS_FETCHED = 'ALL_EVENTS_FETCHED';
export const MY_EVENTS_FETCHED = 'MY_EVENTS_FETCHED';
export const EVENT_UPDATED = 'EVENT_UPDATED';

